language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk11 -params "source=false"
  - C://ProgramData//chocolatey//bin//RefreshEnv.cmd
  - env
script:
  - npm run lint
  - npm run coverage
  - codecov
