language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk11
  - export PATH=$PATH:"/c/Program Files/Java/jdk-11.0.1/bin"
  - java version
script:
  - npm run coverage
