language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk11 -params "source=false"
  - "C:\Program Files\Java\jdk-11.0.1\java" -version
script:
  - npm run lint
  - npm run coverage
  - codecov
