language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk11 -params "source=false"
  - powershell Get-Item Env:Path
  - powershell $CurrPath = Get-Item Env:Path
  - powershell $AddedPath = $CurrPath + 'C:\Program Files\Java\jdk-11.0.1\bin'
  - powershell Set-Item -path env:PATH -value $AddedPath
  - powershell Set-Item -path env:JAVA_HOME -value 'C:\Program Files\Java\jdk-11.0.1\bin'
  - powershell refreshenv
  - env
script:
  - npm run lint
  - npm run coverage
  - codecov
