language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk11 -params "source=false"
  - powershell SET PATH=%PATH%:C:\Program Files\Java\jdk-11.0.1\bin
  - powershell SET JAVA_HOME=C:\Program Files\Java\jdk-11.0.1\bin
  - C://ProgramData//chocolatey//bin//RefreshEnv.cmd
  - env
script:
  - npm run lint
  - npm run coverage
  - codecov
