language: node_js
os:
  - windows
node_js:
  - "11"
  - "10"
before_script:
  - choco install jdk8
  - export PATH=$PATH:"/c/Program Files/Java/jdk-1.8.0_191/bin"
  - java version
script:
  - npm run coverage
